version: '3.8'

services:
  stable-diffusion-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    runtime: nvidia
    volumes:
      - /mnt/efs/saved_sd15:/mnt/efs/saved_sd15
    restart: unless-stopped 